name: Release

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  #;< RELEASEDRAFTER
  release-drafter:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #;> RELEASEDRAFTER
  #;< PHP
  release-php:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Box
        run: |
          export BOX_VERSION="4.3.8"
          wget "https://github.com/humbug/box/releases/download/${BOX_VERSION}/box.phar" --quiet -O ./box
          chmod +x ./box
          sudo mv ./box /usr/local/bin
      - uses: php-actions/composer@v6
      - run: composer build
      - run: ./.build/template-command-script.phar | grep -q "?"
      - name: Get Tag Name
        id: get-version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./.build/template-command-script.phar
  #;> PHP
  #;< NODEJS
  release-nodejs:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install
      - run: npm run build
  #;> NODEJS
