name: Scaffold test

# Workflow to **validate** the **integrity** of the scaffold template itself.
# This workflow will be automatically removed from the scaffolded project
# after running init.sh script.

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
  push:
    branches:
      - main

jobs:
  scaffold-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: tests/scaffold/package-lock.json
    - run: npm --prefix=tests/scaffold ci
    - run: |
        export TMPDIR=$(pwd)/tmp
        mkdir -p ${TMPDIR}
        ./tests/scaffold/node_modules/.bin/bats -t tests/scaffold
    - run: sudo apt-get install -y kcov
    - run: kcov --include-pattern=.bash,.sh --bash-parse-files-in-dir=. --exclude-path=node_modules,vendor,coverage coverage ./tests/scaffold/node_modules/.bin/bats tests/scaffold
    - uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        directory: ./coverage
        fail_ci_if_error: true
