name: Scaffold test

# Workflow to **validate** the **integrity** of the scaffold template itself.
# This workflow will be automatically removed from the scaffolded project
# after running init.sh script.

on:
  pull_request:
    branches:
      - main
      - 'feature/**'
  push:
    branches:
      - main

jobs:
  scaffold-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: luizm/action-sh-checker@v0.7.0
      env:
        SHFMT_OPTS: -i 2 -ci -s -d
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'
        cache-dependency-path: scaffold_tests/package-lock.json
    - run: npm --prefix=scaffold_tests ci
    - run: ./scaffold_tests/node_modules/.bin/bats --print-output-on-failure --formatter tap scaffold_tests
